version: '3'

networks:
  mynetwork:
    driver: bridge
services:
  infinispan-server:
    image: quay.io/infinispan/server:15.0
    volumes:
      - ${PWD}:/user-config
    depends_on:
      - "keycloak"
    ports:
      - "11222:11222"
    container_name: ispn
    environment:
      USER: admin
      PASS: password
    networks:
      - mynetwork
    command: -c infinispan.xml -c /user-config/infinispan-token-realm.yaml
  keycloak:
    image:  quay.io/keycloak/keycloak
    volumes:
      - ${PWD}/infinispan-keycloak-realm.json:/opt/keycloak/data/import/infinispan-keycloak-realm.json
    ports:
      - "8080:8080"
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    command: ['start-dev', '--import-realm']
    networks:
      - mynetwork
