name: Add release label to closed issues
# This GitHub Actions workflow automatically adds the current release as a label to closed
# issues with pull requests that were merged. The value of the current
# release is held in a GitHub organization variable. The GHA also handles backports on
# the 16.0 and 16.1 branches.

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
      - 16.0
      - 16.1

jobs:
  add-release-label:
    runs-on: ubuntu-latest
    outputs:
      issue_urls: ${{ steps.get_linked_issue.outputs.issue_urls }}
      # An array of issue URLs fixed by the merged PR

    steps:
      - name: Get issue linked to merged PR
        if: ${{ github.event.pull_request && github.event.pull_request.merged }}
        # Only run if the PR was merged
        id: get_linked_issue
        shell: bash
        env:
          GH_TOKEN: "${{ secrets.INFINISPAN_RELEASE_TOKEN }}"
        run: >
          echo issue_urls=$(node -pe "try{obj=JSON.parse(
          '$(gh pr view ${{ github.event.pull_request.html_url }} --json closingIssuesReferences)'
          );
          obj.closingIssuesReferences.map(issue => issue.url).toString().replaceAll(',',' ')}
          catch(TypeError){}") >> "$GITHUB_OUTPUT"

      - name: Create label and ignore error if it exists
        shell: bash
        env:
          GH_TOKEN: "${{ secrets. INFINISPAN_RELEASE_TOKEN }}"
        continue-on-error: true
        run: >
          gh label create "release/${{ vars.RELEASE }}"
          --description "Label for issues with PRs merged to main during the Infinispan ${{ vars.RELEASE }} release cycle"

      - name: Label issue
        shell: bash
        env:
          GH_TOKEN: "${{ secrets.INFINISPAN_RELEASE_TOKEN }}"
        run: >
          label="release/${{ vars.RELEASE }}";
          if [[ "${{ github.event.pull_request.base.ref }}" == "16.0" ]];
          then label="release/16.0";
          elif [[ "${{ github.event.pull_request.base.ref }}" == "16.1" ]];
          then label="release/16.1";
          fi;
          declare -a arr=(${{ steps.get_linked_issue.outputs.issue_urls }});
          for issue in "${arr[@]}";
          do gh issue edit $issue --add-label $label;
          done;

