name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The Infinispan Console branch to checkout when cutting the release."
        required: true
        default: "main"
      version:
        description: "Release version"
        required: true
      nextVersion:
        description: "Next version"
        required: true

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set release version
        run: |
          ./mvnw -B versions:set -DnewVersion=${{ github.event.inputs.version }} -DprocessAllModules=true
          ./mvnw -B versions:set-property -Dproperty=version.infinispan -DnewVersion=${{ github.event.inputs.version }}

      - name: Set up Java for publishing to OSSRH
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.INFINISPAN_MAVEN_GPG_ARMORED }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to OSSRH
        run: ./mvnw -B clean deploy -Pcommunity-release -DskipTests -Dinfinispan-console.brand.version=${{ github.event.inputs.version }}
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.INFINISPAN_MAVEN_GPG_PASSPHRASE }}

      - name: Configure Git User
        run: |
          git config user.email "infinispan@infinispan.org"
          git config user.name "Infinispan"

      - name: Tag Release
        run: |
          git commit --no-verify -a -m "Releasing ${{ github.event.inputs.version }}"
          git tag ${{ github.event.inputs.version }}

      - name: Next Version
        run: |
          ./mvnw -B versions:set -DnewVersion=${{ github.event.inputs.nextVersion }} -DprocessAllModules=true
          ./mvnw -B versions:set-property -Dproperty=version.infinispan -DnewVersion=${{ github.event.inputs.nextVersion }}
          git commit --no-verify -a -m "Next version ${{ github.event.inputs.nextVersion }}"

      - name: Push changes
        uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.inputs.branch }}
          tags: true

      - id: release
        name: Create Release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
