apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: mycache-site-b
spec:
  clusterName: example-clusterb
  name: mycache 
  template: |-
    <distributed-cache name="mycache" mode="SYNC">
      <backups>
        <backup site="SiteA" strategy="SYNC" timeout="5000">
          <take-offline after-failures="10" min-wait="10000" />
        </backup>
      </backups>
    </distributed-cache>