apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-clustera
spec:
  replicas: 2
  expose:
    type: NodePort
    nodePort: 30000
  security:
    endpointSecretName: connect-secret-clustera
  service:
    type: DataGrid
    sites:
      local:
        name: SiteA
        expose:
          type: ClusterIP
      locations:
        - name: SiteA
          url: infinispan+xsite://example-clustera-site
        - name: SiteB
          url: infinispan+xsite://example-clusterb-site